// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	device "github.com/rna-vt/devicecommander/src/device"
	mock "github.com/stretchr/testify/mock"

	scanner "github.com/rna-vt/devicecommander/src/scanner"
)

// Cluster is an autogenerated mock type for the Cluster type
type Cluster struct {
	mock.Mock
}

// DeviceDiscovery provides a mock function with given fields: _a0
func (_m *Cluster) DeviceDiscovery(_a0 int) {
	_m.Called(_a0)
}

// HandleDiscoveredDevice provides a mock function with given fields: _a0
func (_m *Cluster) HandleDiscoveredDevice(_a0 scanner.FoundDevice) (device.Device, error) {
	ret := _m.Called(_a0)

	var r0 device.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(scanner.FoundDevice) (device.Device, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(scanner.FoundDevice) device.Device); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(device.Device)
	}

	if rf, ok := ret.Get(1).(func(scanner.FoundDevice) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with given fields:
func (_m *Cluster) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PrintClusterInfo provides a mock function with given fields:
func (_m *Cluster) PrintClusterInfo() {
	_m.Called()
}

// RunHealthCheckLoop provides a mock function with given fields: _a0
func (_m *Cluster) RunHealthCheckLoop(_a0 int) {
	_m.Called(_a0)
}

// Start provides a mock function with given fields:
func (_m *Cluster) Start() {
	_m.Called()
}

// StopDiscovery provides a mock function with given fields:
func (_m *Cluster) StopDiscovery() {
	_m.Called()
}

// StopHealth provides a mock function with given fields:
func (_m *Cluster) StopHealth() {
	_m.Called()
}

// NewCluster creates a new instance of Cluster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCluster(t interface {
	mock.TestingT
	Cleanup(func())
}) *Cluster {
	mock := &Cluster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
