// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	device "github.com/rna-vt/devicecommander/src/device"
	mock "github.com/stretchr/testify/mock"
)

// Cluster is an autogenerated mock type for the Cluster type
type Cluster struct {
	mock.Mock
}

// DeviceDiscovery provides a mock function with given fields: _a0
func (_m *Cluster) DeviceDiscovery(_a0 int) {
	_m.Called(_a0)
}

// HandleDiscoveredDevice provides a mock function with given fields: _a0
func (_m *Cluster) HandleDiscoveredDevice(_a0 device.NewDeviceParams) (device.Device, error) {
	ret := _m.Called(_a0)

	var r0 device.Device
	if rf, ok := ret.Get(0).(func(device.NewDeviceParams) device.Device); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(device.Device)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(device.NewDeviceParams) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Name provides a mock function with given fields:
func (_m *Cluster) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PrintClusterInfo provides a mock function with given fields:
func (_m *Cluster) PrintClusterInfo() {
	_m.Called()
}

// RunHealthCheckLoop provides a mock function with given fields: _a0
func (_m *Cluster) RunHealthCheckLoop(_a0 int) {
	_m.Called(_a0)
}

// Start provides a mock function with given fields:
func (_m *Cluster) Start() {
	_m.Called()
}

// StopDiscovery provides a mock function with given fields:
func (_m *Cluster) StopDiscovery() {
	_m.Called()
}

// StopHealth provides a mock function with given fields:
func (_m *Cluster) StopHealth() {
	_m.Called()
}

// VerifyDeviceAPI provides a mock function with given fields: _a0
func (_m *Cluster) VerifyDeviceAPI(_a0 device.Device) (device.Device, error) {
	ret := _m.Called(_a0)

	var r0 device.Device
	if rf, ok := ret.Get(0).(func(device.Device) device.Device); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(device.Device)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(device.Device) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCluster interface {
	mock.TestingT
	Cleanup(func())
}

// NewCluster creates a new instance of Cluster. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCluster(t mockConstructorTestingTNewCluster) *Cluster {
	mock := &Cluster{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
