// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/rna-vt/devicecommander/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// Cluster is an autogenerated mock type for the Cluster type
type Cluster struct {
	mock.Mock
}

// DeviceDiscovery provides a mock function with given fields: _a0
func (_m *Cluster) DeviceDiscovery(_a0 int) {
	_m.Called(_a0)
}

// HandleDiscoveredDevice provides a mock function with given fields: _a0
func (_m *Cluster) HandleDiscoveredDevice(_a0 model.NewDevice) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.NewDevice) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *Cluster) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PrintClusterInfo provides a mock function with given fields:
func (_m *Cluster) PrintClusterInfo() {
	_m.Called()
}

// RunHealthCheckLoop provides a mock function with given fields: _a0
func (_m *Cluster) RunHealthCheckLoop(_a0 int) {
	_m.Called(_a0)
}

// Start provides a mock function with given fields:
func (_m *Cluster) Start() {
	_m.Called()
}

// StopDiscovery provides a mock function with given fields:
func (_m *Cluster) StopDiscovery() {
	_m.Called()
}

// StopHealth provides a mock function with given fields:
func (_m *Cluster) StopHealth() {
	_m.Called()
}
