run:
  tests: true
  modules-download-mode: vendor
  skip-dirs-use-default: true
# Linter Docs: https://golangci-lint.run/usage/linters/
linters:
  enable:
  - deadcode
  - errcheck
  - goconst
  - gofumpt
  - dupl
  - gci
  - revive
  - gosimple
  - govet
  - ineffassign
  - nakedret
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck
  - whitespace
  - errorlint
  - funlen
  - gocognit
  - gocritic
  - godot
  - gomnd
  - ifshort
  - misspell
  - prealloc
  - unconvert
  - unparam
  - wastedassign
  - gosec
issues:
  exclude-rules:
    - path: mocks/*
      linters:
        - typecheck
    - path: pkg/docs/*
      linters:
        - deadcode
        - unused
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 40
  govet:
    check-shadowing: true
  gci:
    local-prefixes: github.com/rna-vt/devicecommander
  gocritic:
    enabled-checks:
      - nestingReduce
      - unnamedresult
      - ruleguard
      - truncateCmp
  gomnd:
    settings:
      mnd:
        ignored-files: config_env.go
