run:
  tests: true
  modules-download-mode: vendor
  skip-dirs-use-default: true
linters:
  disable-all: true
  enable:
  - deadcode
  - errcheck
  - goconst
  - gofumpt
  - gci
  - revive
  - gosimple
  - govet
  - ineffassign
  - nakedret
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck
  - whitespace
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gci:
    local-prefixes: github.com/rna-vt/devicecommander
