run:
  tests: true
  modules-download-mode: vendor
  skip-dirs-use-default: true
linters:
  enable:
  - deadcode
  - errcheck
  - goconst
  - gofumpt
  - dupl
  - gci
  - revive
  - gosimple
  - govet
  - ineffassign
  - nakedret
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck
  - whitespace
  - errorlint
  # - exhaustivestruct
  - funlen
  - gocognit
  - goconst
  - gocritic
  - godot
  - gomnd
  - ifshort
  - misspell
  - prealloc
  - unconvert
  - unparam
  - wastedassign
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gci:
    local-prefixes: github.com/rna-vt/devicecommander
  gomnd:
    settings:
      mnd:
        # the list of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
        # ignored-numbers: 1000
        ignored-files: config_env.go
        # ignored-functions: ConfigureEnvironment
