run:
  tests: true
  modules-download-mode: vendor
  skip-dirs-use-default: true
linters:
  enable:
  - deadcode
  - errcheck
  - goconst
  - gofumpt
  - dupl
  - gci
  - revive
  - gosimple
  - govet
  - ineffassign
  - nakedret
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck
  - whitespace
  - errorlint
  # - exhaustivestruct
  - funlen
  - gocognit
  - goconst
  - gocritic
  - godot
  # - gomnd
  - ifshort
  - misspell
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  gci:
    local-prefixes: github.com/rna-vt/devicecommander
