# To fetch schema from
introspection: http://localhost:8001/v1/graphql/query

servers: # same format as for OpenAPI Specification
  - url: https://dev-server.com
    description: Dev
  - url: https://prod-server.com
    description: Prod

info: # same format as for OpenAPI Specification
  title: DeviceCommander
  description: This guide will describe the ways in which you can interact with DeviceCommanders graphql endpoint.

 # define your domains by providing a set of usecases
domains:
  - name: Devices
    description: A Device is a building block of the network.  # Description of the domain
    usecases:         
    #  - name: Delete a Device # Operation name
    #    description: This operation will Delete a device and all of its realted objects. # Opearation description
    #    query: query.some # Query example - fetching single field
    #    select: field1 field2 # select only specific sub fields. By default - all are selected
    #    expand: field3(sub1, sub2, sub3),field4 # go deep by expanding specific fields.
     - name: Create Device
       description: Create a new device
       query: mutation.createDevice # Mutation example - invoke mutation
