{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gofire.serviceAccountName" . }}
  labels:
{{ include "gofire.labels" . | nindent 4 }}
{{- end -}}
