// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	device "github.com/rna-vt/devicecommander/src/device"
	mock "github.com/stretchr/testify/mock"
)

// EndpointRepository is an autogenerated mock type for the EndpointRepository type
type EndpointRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *EndpointRepository) Create(_a0 device.NewEndpointParams) (*device.Endpoint, error) {
	ret := _m.Called(_a0)

	var r0 *device.Endpoint
	if rf, ok := ret.Get(0).(func(device.NewEndpointParams) *device.Endpoint); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*device.Endpoint)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(device.NewEndpointParams) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0
func (_m *EndpointRepository) Delete(_a0 string) (*device.Endpoint, error) {
	ret := _m.Called(_a0)

	var r0 *device.Endpoint
	if rf, ok := ret.Get(0).(func(string) *device.Endpoint); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*device.Endpoint)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0
func (_m *EndpointRepository) Get(_a0 device.Endpoint) ([]*device.Endpoint, error) {
	ret := _m.Called(_a0)

	var r0 []*device.Endpoint
	if rf, ok := ret.Get(0).(func(device.Endpoint) []*device.Endpoint); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*device.Endpoint)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(device.Endpoint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *EndpointRepository) GetAll() ([]*device.Endpoint, error) {
	ret := _m.Called()

	var r0 []*device.Endpoint
	if rf, ok := ret.Get(0).(func() []*device.Endpoint); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*device.Endpoint)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *EndpointRepository) Update(_a0 device.UpdateEndpointParams) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(device.UpdateEndpointParams) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
