this_node:
  - parts:
    - name: sign_supply
      type: supply
      gpio_pin: 38
      sources:
      - grid_supply
      inverted_output_device: true
    - name: sign_manifold
      type: supply
      gpio_pin: 36
      sources:
      - sign_manifold
      inverted_output_device: true
    - name: sign_0
      type: outlet
      gpio_pin: 32
      sources:
      - sign_manifold
      inverted_output_device: true
    - name: sign_2
      type: outlet
      gpio_pin: 39
      sources:
      - sign_manifold
      inverted_output_device: true
    - name: sign_3
      type: outlet
      gpio_pin: 41
      sources:
      - sign_manifold
      inverted_output_device: true
    - name: sign_4
      type: outlet
      gpio_pin: 44
      sources:
      - sign_manifold
      inverted_output_device: true