// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewDevice struct {
	Mac         *string `json:"MAC"`
	Name        *string `json:"Name"`
	Description *string `json:"Description"`
	Host        string  `json:"Host"`
	Port        int     `json:"Port"`
	Active      *bool   `json:"Active"`
}

type NewEndpoint struct {
	DeviceID    string       `json:"DeviceID"`
	Name        *string      `json:"Name"`
	Type        string       `json:"Type"`
	Description *string      `json:"Description"`
	Path        *string      `json:"Path"`
	Parameters  []*Parameter `json:"Parameters"`
}

type Parameter struct {
	ID          string  `json:"ID"`
	Key         string  `json:"Key"`
	EndpointID  string  `json:"EndpointID"`
	Description *string `json:"Description"`
	Type        string  `json:"Type"`
}

type UpdateDevice struct {
	ID          string  `json:"ID"`
	Mac         *string `json:"MAC"`
	Name        *string `json:"Name"`
	Description *string `json:"Description"`
	Host        *string `json:"Host"`
	Port        *int    `json:"Port"`
	Active      *bool   `json:"Active"`
}

type UpdateEndpoint struct {
	ID          string  `json:"ID"`
	DeviceID    *string `json:"DeviceID"`
	Name        *string `json:"Name"`
	Type        *string `json:"Type"`
	Description *string `json:"Description"`
	Path        *string `json:"Path"`
}
