// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import (
	scanner "github.com/rna-vt/devicecommander/pkg/scanner"
	mock "github.com/stretchr/testify/mock"
)

// Scanner is an autogenerated mock type for the Scanner type
type Scanner struct {
	mock.Mock
}

// Scan provides a mock function with given fields:
func (_m *Scanner) Scan() ([]scanner.FoundDevice, error) {
	ret := _m.Called()

	var r0 []scanner.FoundDevice
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]scanner.FoundDevice, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []scanner.FoundDevice); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scanner.FoundDevice)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewScanner creates a new instance of Scanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Scanner {
	mock := &Scanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
