apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gofire
spec:
  selector:
    matchLabels:
      app: gofire
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: gofire
    spec:
      containers:
        - name: gofire-app
          image: dtp263/gofire:v1
          resources:
            limits:
              cpu: 200m
              memory: 32Mi
            requests:
              cpu: 200m
              memory: 32Mi
          imagePullPolicy: Always
          command: ["go"]
          args: ["run", "main.go"]
          restartPolicy: OnFailure
          env:
            - name: GOFIRE_MASTER
              value: "TRUE"
          ports:
            - containerPort: 8001
