// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	model "github.com/rna-vt/devicecommander/src/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// ParameterCRUDRepository is an autogenerated mock type for the ParameterCRUDRepository type
type ParameterCRUDRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *ParameterCRUDRepository) Create(_a0 model.NewParameter) (*model.Parameter, error) {
	ret := _m.Called(_a0)

	var r0 *model.Parameter
	if rf, ok := ret.Get(0).(func(model.NewParameter) *model.Parameter); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Parameter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.NewParameter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0
func (_m *ParameterCRUDRepository) Delete(_a0 string) (*model.Parameter, error) {
	ret := _m.Called(_a0)

	var r0 *model.Parameter
	if rf, ok := ret.Get(0).(func(string) *model.Parameter); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Parameter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0
func (_m *ParameterCRUDRepository) Get(_a0 model.Parameter) ([]*model.Parameter, error) {
	ret := _m.Called(_a0)

	var r0 []*model.Parameter
	if rf, ok := ret.Get(0).(func(model.Parameter) []*model.Parameter); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Parameter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(model.Parameter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *ParameterCRUDRepository) GetAll() ([]*model.Parameter, error) {
	ret := _m.Called()

	var r0 []*model.Parameter
	if rf, ok := ret.Get(0).(func() []*model.Parameter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Parameter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *ParameterCRUDRepository) Update(_a0 model.UpdateParameter) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.UpdateParameter) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
